### ISSUE TITLE
Test 2.0 across Windows editions

### ISSUE THREAD

**Issue by vweevers** [vweevers/win-detect-browsers#17]
- [x] Windows Server 2012 R2 (`--no-operaversions`), x86, x64, node 0.11.16, iojs 1.8.1
- [x] Windows 8.1 (`--no-operaversions`), x64, node 0.12.1
- [x] Windows 7, x86, node 0.10.35
- [x] Windows XP Pro (`--no-operaversions`), x86, node 0.10.38, 0.11.16, 0.12.2, iojs 1.8.1

**Comment by vweevers** [comment]
For future reference, here is a batch file that runs the test suite on different versions of nodejs, using `nvmw`. If those versions are not yet installed, replace `nvmw use` with `nvmw install`. The machine should have Chrome, FF, IE and Opera installed.

```batch
@echo off

call nvmw use iojs

call git clone https://github.com/vweevers/win-detect-browsers.git wdb
cd wdb
call git checkout 2.0
call npm i
set debug=

call :test
call nvmw use v0.10.38
call :test
call nvmw use v0.11.16
call :test
call nvmw use v0.12.2
call :test

cd ..
goto :eof

:test
call npm i tape tap-spec -g
call tape test.js --no-operaversions | tap-spec
```

**Comment by kostasmanionis** [comment]
Can confirm that it works fine on `Windows 8.1 x64 with Node 0.12.1`. Ran the test,js whith `--no-operaversions` flag. All passed. Found these browsers, which is correct.

```
chrome 44.0.2390.0
  @ C:\Users\Mobile\AppData\Local\Google\Chrome SxS\Application\chrome.exe

chrome 42.0.2311.90
  @ C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

firefox 37.0.2.5583
  @ C:\Program Files (x86)\Mozilla Firefox\firefox.exe

ie 11.0.9600.17416
  @ C:\Program Files (x86)\Internet Explorer\iexplore.exe

ie 11.0.9600.17416
  @ C:\Program Files\Internet Explorer\iexplore.exe

opera 29.0.1795.47
  @ C:\Program Files (x86)\Opera\Launcher.exe

phantomjs 1.9.8.0
  @ c:\Users\Mobile\Documents\GitHub\win-detect-browsers\node_modules\phantomjs\
lib\phantom\phantomjs.exe
```

**Comment by vweevers** [comment]
@kostasmanionis Nice, thanks.

**Comment by vweevers** [comment]
This should suffice; I didn't encounter any problems or Windows weirdness. I've copied the reports to the [wiki](https://github.com/vweevers/win-detect-browsers/wiki), so that anyone can add their own.
