### ISSUE TITLE
Is it possible to add support of Yandex.Browser?

### ISSUE THREAD

**Issue by shytikov** [vweevers/win-detect-browsers#19]
It's a chrome fork - https://browser.yandex.com/

**Comment by vweevers** [comment]
PR is welcome. Take a look at [browsers.js](https://github.com/vweevers/win-detect-browsers/blob/master/lib/browsers.js). You'd need to add `exports.yandex = ..` with default install location(s), registry keys, etc. Provided those paths and keys don't conflict with chrome's.

**Comment by shytikov** [comment]
Thanks for manual, will try to add support for Yandex and maybe other (major, good quality) local browsers, like Chinese Maxthon, for example.

**Comment by shytikov** [comment]
I have tested locally (did not modified your unit tests included). It works for both standard or custom installation (custom path) of the browsers.
