### ISSUE TITLE
Differentiate Chrome Canary and Firefox Dev Edition

### ISSUE THREAD

**Issue by tomitm** [vweevers/win-detect-browsers#22]
Chrome Canary and Firefox Dev Edition are their own standalone installations that run alongside their respective stable/beta channel installations. This is similar to Chromium which this library identifies separately, although I guess Chromium is a different product, whereas the canaries aren't.

Right now, they're detected as a second `chrome`/`firefox` result with different version numbers, but would you be open to differentiating them as `chrome-canary` and `firefox-dev`?

I imagine this might be a breaking change if people are relying on this behaviour already, so I figured I'd ask before I work on writing a PR for this change. Thanks!

**Comment by jakub-g** [comment]
Yes I think it would be interesting to differentiate them.

Maybe the detection method / detection script could accept a param / command line param to tell whether you want to have those items merged or separated; if not specified, then it by default merges all into `chrome` / `firefox` for backward compat?

**Comment by vweevers** [comment]
I'm not sure this is a good idea. I like simple data, from which a consumer can derive extra information if needed. Like looking at the version number to see if it's a beta release or not. You could write a new module for this, one that isn't tied to Windows.

How would you differentiate, if not by version number? For example: if I only got Chrome stable installed, the registry key `HKLM\Software\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe` would have the value `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`. If I install Canary too, that same key would have the value `C:\Users\vweevers\AppData\Local\Google\Chrome SxS\Application\chrome.exe`.

That `win-detect-browsers` can detect the canaries, even when they're installed at a non-default location, is *because* their registry keys clash with the stable release channels.

**Comment by tomitm** [comment]
It looks like you use `Classes\\ChromeHTML\\shell\\open\\command` to find the main install. I found `ChromeSSHTM.SCXTU77WPPCZZWL7LX4LSWLZ34` beside it for canary (assuming you can use a wildcard). Unlike the `App Paths` key, that one doesn't clash. Or is the key under `Classes` not guaranteed to be there?

Firefox looks like it uses `Firefox Developer Edition` in place of `Mozilla Firefox`, so that seems straight-forward as well.

I noticed that it seems to be possible to figure out if a Chrome install is stable/beta/dev/canary via the updater. The keys `HKCU\SOFTWARE\Google\Update\ClientState\{...}\ap` and `HKLM\SOFTWARE\WOW6432Node\Google\Update\ClientState\{...}\ap` have the value of `x64-dev-multi-install` or `x64-canary` for me (*multi-install* denotes it's installed under AppData).

Unfortunately, I can't seem to find if Firefox has similar info available, other than the default vs Dev Edition bit.

Another option is appending the channel to the version, but that might be breaking depending onhow consumers use the version. Could also add a new 'channel' property for stable/beta/dev/canary, instead of returning a different name, so it wouldn't be a breaking change.

Completely understand if you'd rather keep it simple and not include this info. The only downside is since paths are returned, which are unreliable, consumers don't really have any way of knowing if a given result is stable/beta/dev/canary without some sort of outside knowledge of versions.

**Comment by mitchhentges** [comment]
> I'm not sure this is a good idea. I like simple data, from which a consumer can derive extra information if needed. Like looking at the version number to see if it's a beta release or not.

Unfortunately, `win-detect-browsers` doesn't provide enough information for consumers to derive the extra information needed. The most unique value provided is the `path`, but I'm not sure that consumers should take care of differentiating between versions simply by using the path or invoking the binaries and parsing output: isn't that more "detection"? :wink:

Having a `channel` property which is `'canary'|'developer'|'beta'|undefined` (or having the information in `name`) would be great :)

**Comment by vweevers** [comment]
My schedule's full, but I wanted you let you know I see the value of a `channel` property, I acknowledge the problem, and have a solution in mind. Sorry I can't give a in-depth response right now.

@tomitm @mitchhentges How blocked are you by this?

**Comment by mitchhentges** [comment]
Not super blocked. Right now, [James](https://github.com/james-proxy/james) shows a full browser name on Linux/Mac, but on Windows, it can only show the browser type. It's not that bad, and nobody is that bent out of shape about it.

So, about 1% blocked on this :wink:

**Comment by vweevers** [comment]
Okay. Ah, you and @tomitm are part of the same team. Makes sense.

**Comment by tomitm** [comment]
Great to hear, @vweevers. I can submit a PR for this, if you'd like, just point me in the right direction!

**Comment by vweevers** [comment]
See #23, #24 and #25.

**Comment by tomitm** [comment]
Thanks @vweevers :+1:
