### ISSUE TITLE
In the example,miss a )

### ISSUE THREAD

**Issue by lavystord** [vweevers/win-detect-browsers#27]
In the wiki,it writes as here:
Detect everything:

var detect   = require('win-detect-browsers')
  , through2 = require('through2')

detect().pipe(through2.obj(function(b, _, next){
  var format = "\n%s %s\n  @ %s"
  console.log(format, b.name, b.version, b.path)
  next()
})

Actually,right one should be
 next()
}))

**Comment by vweevers** [comment]
Good catch, thanks.
