### ISSUE TITLE
Release the current master

### ISSUE THREAD

**Issue by pimterry** [vweevers/win-detect-browsers#43]
I'm working on updating to the latest win-detect-browsers to fix https://github.com/james-proxy/james-browser-launcher/issues/83, but for my case I easily can't do native builds. Registry-js does now provide prebuilt binaries, which would work, but the version that the latest released versions depends on (`~1.0.7`) does not.

An update to `~1.4.0` is already on master, and it looks like that would fix this. Is there any reason not to release that change? Let me know if there's anything I can do to help.

**Comment by vweevers** [comment]
> Is there any reason not to release that change?

I dropped node 6 on master, so the next version will be a major. And because https://github.com/vweevers/win-detect-browsers/issues/33 is also a breaking change, I want to squeeze that in. Small task, just didn't get to it yet.

I should also update [`win-version-info`](https://github.com/vweevers/win-version-info), to add prebuilds for node 12.

**Comment by vweevers** [comment]
(PRs for either are welcome!)

**Comment by vweevers** [comment]
Hmm, the latest version of `registry-js` is 1.5.0, which [dropped prebuilds for node 8](https://github.com/desktop/registry-js/commit/dbceb16f9be1d8e7ffbf38bf067bb57a3ae71f63) 😞

**Comment by pimterry** [comment]
> because #33 is also a breaking change, I want to squeeze that in

> I should also update win-version-info, to add prebuilds for node 12.

PRs opened for both :+1:

> Hmm, the latest version of registry-js is 1.5.0, which dropped prebuilds for node 8 disappointed

Not a problem from my POV, but I can totally see how that's a concern. Sticking with 1.4.0 for now should work though, right? No major differences that I can see.

Officially Node 10 is the current LTS version and Node 8 is maintenance-only, and 8 will be unsupported entirely from the end of this year, so dropping support at that point would make sense, I imagine.

**Comment by vweevers** [comment]
> Sticking with 1.4.0 for now should work though, right? [.. ] and 8 will be unsupported entirely from the end of this year, so dropping support at that point would make sense

👍

**Comment by vweevers** [comment]
Released 4.0.0. Thanks @pimterry!

**Comment by pimterry** [comment]
Amazing, thank you!
