### ISSUE TITLE
Handle access denied errors

### ISSUE THREAD

**Issue by pimterry** [vweevers/win-detect-browsers#64]
If a user doesn't have access to read some registry keys, they can get a synchronous error, which is unhandled, and which thus crashes the process. See https://github.com/httptoolkit/feedback/issues/50 for an example.

Imo, in this case we should just ignore the information from that registry key, and move on, rather than failing entirely. It's safe to do so I believe, it just reduces the amount of info (e.g. uninstaller paths) we can return.

I'm happy to open a PR for this, just checking it would be welcomed first. My suggestion would be to just change `enumerateValues` to [`enumerateValuesSafe`](https://github.com/desktop/registry-js/blob/master/lib/registry.ts#L104), which automatically returns `[]` if any registry values can't be read. I've given this a quick test locally and it seems to work very nicely, and still detects other browser info as normal. Sound good?

**Comment by vweevers** [comment]
I wasn't aware `enumerateValuesSafe` existed! Let's use it.

(As for your other PR, I'll have a look tomorrow)

**Comment by vweevers** [comment]
Fixed by #65.
