### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by mdimranpatel250** [vweevers/win-detect-browsers#72]
in pen drive your library not working plz help me

**Comment by vweevers** [comment]
I'm gonna need more info than that.

**Comment by mdimranpatel250** [comment]
actually my project shift to one pen drive from pen drive i m running node js  application
in pen drive not opening application if i remove win-detect-browser command line  its working otherwise its not working in c drive is working and in d drive is not working

**Comment by vweevers** [comment]
Still need more info. What is not working? What error do you get? Can you share stack traces, logs, a code example? What do you mean by "win-detect-browser command line"? Which version of node and `win-detect-browsers` do you use?
